<?php

/**
 * @file
 * Module file for views_lazy_load.module.
 */

/**
 * Implements hook_theme().
 */
function views_lazy_load_theme() {
  return array(
    'views_lazy_load_throbber' => [
      'variables' => [],
    ],
  );
}

/**
 * Gets a regular expression of user agents to exclude.
 *
 * @return string
 *   A regex string to exclude user agents that don't use Views Lazy Load.
 */
function views_lazy_load_get_excluded_user_agents() {
  return variable_get('views_lazy_load_excluded_user_agents', 'Googlebot|msnbot|Rambler|Yahoo|AbachoBOT|accoona|AcioRobot|APSeek|CocoCrawler|Dumbot|FAST-WebCrawler|GeonaBot|Gigabot|Lycos|MSRBOT|Scooter|AltaVista|IDBot|eStyle|Scrubby');
}
