<?php

/**
 * @file
 * Module file for views_lazy_load.module.
 */


/**
 * Implements hook_views_api().
 */
function views_lazy_load_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_lazy_load') . '/includes/views',
  );
}

/**
 * Implements hook_theme().
 */
function views_lazy_load_theme() {
  return array(
    'views_lazy_load_throbber' => array(),
  );
}

/**
 * Theme callback.
 */
function theme_views_lazy_load_throbber() {
  return '<div class="views-lazy-load">Loading...</div>';
}

/**
 * Implements hook_html_head_alter().
 */
function views_html_head_alter() {
  if (variable_get('views_lazy_load_disable_alerts', FALSE)) {
    drupal_add_js(drupal_get_path('module', 'views_lazy_load') . '/js/disable-alert.js', array('every_page' => TRUE));
  }
}
